//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using AutoReservation.Common.DataTransferObjects;

namespace AutoReservationAdmin.AutoReservationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AutoReservationService.IAutoReservationService")]
    public interface IAutoReservationService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/getAllCars", ReplyAction="http://tempuri.org/IAutoReservationService/getAllCarsResponse")]
        AutoReservation.Common.DataTransferObjects.AutoDto[] getAllCars();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/getAllCars", ReplyAction="http://tempuri.org/IAutoReservationService/getAllCarsResponse")]
        System.Threading.Tasks.Task<AutoReservation.Common.DataTransferObjects.AutoDto[]> getAllCarsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/getAllCustomers", ReplyAction="http://tempuri.org/IAutoReservationService/getAllCustomersResponse")]
        AutoReservation.Common.DataTransferObjects.KundeDto[] getAllCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/getAllCustomers", ReplyAction="http://tempuri.org/IAutoReservationService/getAllCustomersResponse")]
        System.Threading.Tasks.Task<AutoReservation.Common.DataTransferObjects.KundeDto[]> getAllCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/getAllReservations", ReplyAction="http://tempuri.org/IAutoReservationService/getAllReservationsResponse")]
        AutoReservation.Common.DataTransferObjects.ReservationDto[] getAllReservations();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/getAllReservations", ReplyAction="http://tempuri.org/IAutoReservationService/getAllReservationsResponse")]
        System.Threading.Tasks.Task<AutoReservation.Common.DataTransferObjects.ReservationDto[]> getAllReservationsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/getCarById", ReplyAction="http://tempuri.org/IAutoReservationService/getCarByIdResponse")]
        AutoReservation.Common.DataTransferObjects.AutoDto getCarById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/getCarById", ReplyAction="http://tempuri.org/IAutoReservationService/getCarByIdResponse")]
        System.Threading.Tasks.Task<AutoReservation.Common.DataTransferObjects.AutoDto> getCarByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/getCustomerById", ReplyAction="http://tempuri.org/IAutoReservationService/getCustomerByIdResponse")]
        AutoReservation.Common.DataTransferObjects.KundeDto getCustomerById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/getCustomerById", ReplyAction="http://tempuri.org/IAutoReservationService/getCustomerByIdResponse")]
        System.Threading.Tasks.Task<AutoReservation.Common.DataTransferObjects.KundeDto> getCustomerByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/getReservationByNr", ReplyAction="http://tempuri.org/IAutoReservationService/getReservationByNrResponse")]
        AutoReservation.Common.DataTransferObjects.ReservationDto getReservationByNr(int nr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/getReservationByNr", ReplyAction="http://tempuri.org/IAutoReservationService/getReservationByNrResponse")]
        System.Threading.Tasks.Task<AutoReservation.Common.DataTransferObjects.ReservationDto> getReservationByNrAsync(int nr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/addCar", ReplyAction="http://tempuri.org/IAutoReservationService/addCarResponse")]
        void addCar(AutoReservation.Common.DataTransferObjects.AutoDto autoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/addCar", ReplyAction="http://tempuri.org/IAutoReservationService/addCarResponse")]
        System.Threading.Tasks.Task addCarAsync(AutoReservation.Common.DataTransferObjects.AutoDto autoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/addCustomer", ReplyAction="http://tempuri.org/IAutoReservationService/addCustomerResponse")]
        void addCustomer(AutoReservation.Common.DataTransferObjects.KundeDto kundeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/addCustomer", ReplyAction="http://tempuri.org/IAutoReservationService/addCustomerResponse")]
        System.Threading.Tasks.Task addCustomerAsync(AutoReservation.Common.DataTransferObjects.KundeDto kundeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/addRerservation", ReplyAction="http://tempuri.org/IAutoReservationService/addRerservationResponse")]
        void addRerservation(AutoReservation.Common.DataTransferObjects.ReservationDto reservationDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/addRerservation", ReplyAction="http://tempuri.org/IAutoReservationService/addRerservationResponse")]
        System.Threading.Tasks.Task addRerservationAsync(AutoReservation.Common.DataTransferObjects.ReservationDto reservationDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/modifyCar", ReplyAction="http://tempuri.org/IAutoReservationService/modifyCarResponse")]
        void modifyCar(AutoReservation.Common.DataTransferObjects.AutoDto autoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/modifyCar", ReplyAction="http://tempuri.org/IAutoReservationService/modifyCarResponse")]
        System.Threading.Tasks.Task modifyCarAsync(AutoReservation.Common.DataTransferObjects.AutoDto autoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/modifyCustomer", ReplyAction="http://tempuri.org/IAutoReservationService/modifyCustomerResponse")]
        void modifyCustomer(AutoReservation.Common.DataTransferObjects.KundeDto kundeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/modifyCustomer", ReplyAction="http://tempuri.org/IAutoReservationService/modifyCustomerResponse")]
        System.Threading.Tasks.Task modifyCustomerAsync(AutoReservation.Common.DataTransferObjects.KundeDto kundeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/modifyRerservation", ReplyAction="http://tempuri.org/IAutoReservationService/modifyRerservationResponse")]
        void modifyRerservation(AutoReservation.Common.DataTransferObjects.ReservationDto reservationDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/modifyRerservation", ReplyAction="http://tempuri.org/IAutoReservationService/modifyRerservationResponse")]
        System.Threading.Tasks.Task modifyRerservationAsync(AutoReservation.Common.DataTransferObjects.ReservationDto reservationDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/removeCar", ReplyAction="http://tempuri.org/IAutoReservationService/removeCarResponse")]
        void removeCar(AutoReservation.Common.DataTransferObjects.AutoDto autoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/removeCar", ReplyAction="http://tempuri.org/IAutoReservationService/removeCarResponse")]
        System.Threading.Tasks.Task removeCarAsync(AutoReservation.Common.DataTransferObjects.AutoDto autoDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/removeCustomer", ReplyAction="http://tempuri.org/IAutoReservationService/removeCustomerResponse")]
        void removeCustomer(AutoReservation.Common.DataTransferObjects.KundeDto kundeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/removeCustomer", ReplyAction="http://tempuri.org/IAutoReservationService/removeCustomerResponse")]
        System.Threading.Tasks.Task removeCustomerAsync(AutoReservation.Common.DataTransferObjects.KundeDto kundeDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/removeRerservation", ReplyAction="http://tempuri.org/IAutoReservationService/removeRerservationResponse")]
        void removeRerservation(AutoReservation.Common.DataTransferObjects.ReservationDto reservationDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/removeRerservation", ReplyAction="http://tempuri.org/IAutoReservationService/removeRerservationResponse")]
        System.Threading.Tasks.Task removeRerservationAsync(AutoReservation.Common.DataTransferObjects.ReservationDto reservationDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/isCarAvailable", ReplyAction="http://tempuri.org/IAutoReservationService/isCarAvailableResponse")]
        bool isCarAvailable(AutoReservation.Common.DataTransferObjects.ReservationDto reservation, AutoReservation.Common.DataTransferObjects.AutoDto auto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutoReservationService/isCarAvailable", ReplyAction="http://tempuri.org/IAutoReservationService/isCarAvailableResponse")]
        System.Threading.Tasks.Task<bool> isCarAvailableAsync(AutoReservation.Common.DataTransferObjects.ReservationDto reservation, AutoReservation.Common.DataTransferObjects.AutoDto auto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutoReservationServiceChannel : AutoReservationAdmin.AutoReservationService.IAutoReservationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutoReservationServiceClient : System.ServiceModel.ClientBase<AutoReservationAdmin.AutoReservationService.IAutoReservationService>, AutoReservationAdmin.AutoReservationService.IAutoReservationService {
        
        public AutoReservationServiceClient() {
        }
        
        public AutoReservationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutoReservationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoReservationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutoReservationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public AutoReservation.Common.DataTransferObjects.AutoDto[] getAllCars() {
            return base.Channel.getAllCars();
        }
        
        public System.Threading.Tasks.Task<AutoReservation.Common.DataTransferObjects.AutoDto[]> getAllCarsAsync() {
            return base.Channel.getAllCarsAsync();
        }
        
        public AutoReservation.Common.DataTransferObjects.KundeDto[] getAllCustomers() {
            return base.Channel.getAllCustomers();
        }
        
        public System.Threading.Tasks.Task<AutoReservation.Common.DataTransferObjects.KundeDto[]> getAllCustomersAsync() {
            return base.Channel.getAllCustomersAsync();
        }
        
        public AutoReservation.Common.DataTransferObjects.ReservationDto[] getAllReservations() {
            return base.Channel.getAllReservations();
        }
        
        public System.Threading.Tasks.Task<AutoReservation.Common.DataTransferObjects.ReservationDto[]> getAllReservationsAsync() {
            return base.Channel.getAllReservationsAsync();
        }
        
        public AutoReservation.Common.DataTransferObjects.AutoDto getCarById(int id) {
            return base.Channel.getCarById(id);
        }
        
        public System.Threading.Tasks.Task<AutoReservation.Common.DataTransferObjects.AutoDto> getCarByIdAsync(int id) {
            return base.Channel.getCarByIdAsync(id);
        }
        
        public AutoReservation.Common.DataTransferObjects.KundeDto getCustomerById(int id) {
            return base.Channel.getCustomerById(id);
        }
        
        public System.Threading.Tasks.Task<AutoReservation.Common.DataTransferObjects.KundeDto> getCustomerByIdAsync(int id) {
            return base.Channel.getCustomerByIdAsync(id);
        }
        
        public AutoReservation.Common.DataTransferObjects.ReservationDto getReservationByNr(int nr) {
            return base.Channel.getReservationByNr(nr);
        }
        
        public System.Threading.Tasks.Task<AutoReservation.Common.DataTransferObjects.ReservationDto> getReservationByNrAsync(int nr) {
            return base.Channel.getReservationByNrAsync(nr);
        }
        
        public void addCar(AutoReservation.Common.DataTransferObjects.AutoDto autoDto) {
            base.Channel.addCar(autoDto);
        }
        
        public System.Threading.Tasks.Task addCarAsync(AutoReservation.Common.DataTransferObjects.AutoDto autoDto) {
            return base.Channel.addCarAsync(autoDto);
        }
        
        public void addCustomer(AutoReservation.Common.DataTransferObjects.KundeDto kundeDto) {
            base.Channel.addCustomer(kundeDto);
        }
        
        public System.Threading.Tasks.Task addCustomerAsync(AutoReservation.Common.DataTransferObjects.KundeDto kundeDto) {
            return base.Channel.addCustomerAsync(kundeDto);
        }
        
        public void addRerservation(AutoReservation.Common.DataTransferObjects.ReservationDto reservationDto) {
            base.Channel.addRerservation(reservationDto);
        }
        
        public System.Threading.Tasks.Task addRerservationAsync(AutoReservation.Common.DataTransferObjects.ReservationDto reservationDto) {
            return base.Channel.addRerservationAsync(reservationDto);
        }
        
        public void modifyCar(AutoReservation.Common.DataTransferObjects.AutoDto autoDto) {
            base.Channel.modifyCar(autoDto);
        }
        
        public System.Threading.Tasks.Task modifyCarAsync(AutoReservation.Common.DataTransferObjects.AutoDto autoDto) {
            return base.Channel.modifyCarAsync(autoDto);
        }
        
        public void modifyCustomer(AutoReservation.Common.DataTransferObjects.KundeDto kundeDto) {
            base.Channel.modifyCustomer(kundeDto);
        }
        
        public System.Threading.Tasks.Task modifyCustomerAsync(AutoReservation.Common.DataTransferObjects.KundeDto kundeDto) {
            return base.Channel.modifyCustomerAsync(kundeDto);
        }
        
        public void modifyRerservation(AutoReservation.Common.DataTransferObjects.ReservationDto reservationDto) {
            base.Channel.modifyRerservation(reservationDto);
        }
        
        public System.Threading.Tasks.Task modifyRerservationAsync(AutoReservation.Common.DataTransferObjects.ReservationDto reservationDto) {
            return base.Channel.modifyRerservationAsync(reservationDto);
        }
        
        public void removeCar(AutoReservation.Common.DataTransferObjects.AutoDto autoDto) {
            base.Channel.removeCar(autoDto);
        }
        
        public System.Threading.Tasks.Task removeCarAsync(AutoReservation.Common.DataTransferObjects.AutoDto autoDto) {
            return base.Channel.removeCarAsync(autoDto);
        }
        
        public void removeCustomer(AutoReservation.Common.DataTransferObjects.KundeDto kundeDto) {
            base.Channel.removeCustomer(kundeDto);
        }
        
        public System.Threading.Tasks.Task removeCustomerAsync(AutoReservation.Common.DataTransferObjects.KundeDto kundeDto) {
            return base.Channel.removeCustomerAsync(kundeDto);
        }
        
        public void removeRerservation(AutoReservation.Common.DataTransferObjects.ReservationDto reservationDto) {
            base.Channel.removeRerservation(reservationDto);
        }
        
        public System.Threading.Tasks.Task removeRerservationAsync(AutoReservation.Common.DataTransferObjects.ReservationDto reservationDto) {
            return base.Channel.removeRerservationAsync(reservationDto);
        }
        
        public bool isCarAvailable(AutoReservation.Common.DataTransferObjects.ReservationDto reservation, AutoReservation.Common.DataTransferObjects.AutoDto auto) {
            return base.Channel.isCarAvailable(reservation, auto);
        }
        
        public System.Threading.Tasks.Task<bool> isCarAvailableAsync(AutoReservation.Common.DataTransferObjects.ReservationDto reservation, AutoReservation.Common.DataTransferObjects.AutoDto auto) {
            return base.Channel.isCarAvailableAsync(reservation, auto);
        }

        internal ReservationDto getCustomerById(object id)
        {
            throw new NotImplementedException();
        }
    }
}
